ARRAY_HEIGHT = 32
ARRAY_WIDTH = 64
# Clockface colors go from min to max to min throughout the day
DAILY_R_MIN = 5
DAILY_G_MIN = 0
DAILY_B_MIN = 0
DAILY_R_MAX = 50
DAILY_G_MAX = 50
DAILY_B_MAX = 50
BRIGHTNESS_START_HOUR = 6
BRIGHTNESS_END_HOUR = 23
DAILY_BRIGHTNESS_MIN = 5
DAILY_BRIGHTNESS_MAX = 50
SUN_ANIMATION_DURATION = 600  # Seconds
