ARRAY_HEIGHT = 32
ARRAY_WIDTH = 64
# Clockface colors go from min to max to min throughout the day
DAILY_R_MIN = 5
DAILY_G_MIN = 0
DAILY_B_MIN = 0
DAILY_R_MAX = 50
DAILY_G_MAX = 50
DAILY_B_MAX = 50
DEFAULT_SUNRISE_HOUR = 6
DEFAULT_SUNSET_HOUR = 19
BLOOM_START_HOUR_OFFSET = 0  # Offset from sunrise
BLOOM_END_HOUR_OFFSET = 3  # Offset from sunset
DAILY_BRIGHTNESS_MIN = 2
DAILY_BRIGHTNESS_MAX = 50
SUN_ANIMATION_DURATION = 600  # Seconds
